### ISSUE TITLE
Surat Masuk: Tambahkan Tanggal Surat Dibaca

### ISSUE THREAD

**Issue by misnawm** [statsulbardev/silatik#26]
Tambahkan tanggal membaca surat pada masing-masing user di halaman Surat Masuk agar user mengetahui surat ini sudah dibaca di tanggal berapa, jika tanggal kosong berarti surat belum pernah dibaca

**Comment by ipulmisaja** [comment]
dihalaman daftar surat cuma ditambahkan status baca/belum baca surat. Untuk tanggal baca tidak ditampilkan pada halaman daftar surat, tetapi pada detail surat.
