### ISSUE TITLE
Penambahan surat yg akan di upload

### ISSUE THREAD

**Issue by adhyisba** [statsulbardev/silatik#29]
![image](https://user-images.githubusercontent.com/110506245/182537559-4c56d68c-70c4-4ee7-8931-4e94dbf16eb3.png)
pada saat ingin upload surat dan lampirannya, hanya 1 yg bisa terupload. apakah bisa ditambahkan untuk 2 surat

**Comment by ipulmisaja** [comment]
apakah tidak bisa surat dan lampirannya digabung menjadi satu file saja ?
