### ISSUE TITLE
tidak tersave di entrian pak syukur

### ISSUE THREAD

**Issue by adhyisba** [statsulbardev/silatik#30]
pada saat pak syukur entri surat, tdk muncul surat yang sdh dientri. jadi pak syukur tdk tau apakah ibu sdh dispo atau belum

**Comment by ipulmisaja** [comment]
boleh diinformasikan suratnya tanggal berapa dan perihalnya apa ?

**Comment by ipulmisaja** [comment]
suratnya tersimpan, tetapi tidak muncul di halaman pak syukur
